#! /bin/sh
# Jan 2022, Andrew updated it so it can use multiple cores (email Jan 12, 2022)
# Jan 2012, this is mostly from Andrew.  This script takes a directory name as input and compresses individually every file unless it's already been compressed with bz2 or gz
directoryname=$1

#test if no argument are given
if [ $# -eq 0 ]; then
  echo "No arguments provided, this dangerous because the script with act on every file it can find, exiting"
  exit 1
fi

cores=6 # number of cores to use when running
find $directoryname -type f -not \( -name '*.bz2' -o -name '*.gz' \) -print0 | xargs -0 -P $cores -n 3 bzip2 -f
