#!/bin/bash
# ug = update google -
# ugl = update local folder with remote folder data

LOCALROOT="/home/peter/local_GoogleDrive/" #root directory of local folder
REMOTEROOT="/home/peter/GoogleDrive/" #root directory of GoogleDrive folder

### Test if command line argument has been provided and set to and from folder
### path accordingly
if [ "$1" == "-h" ] # looking for help
then
  echo "This script updates folder $LOCALROOT with the content of $REMOTEROOT with deletion"
  echo "By default all the folders are updated, but a specific folder can be specied on the command line"
  echo "The command that will executed by default is:"
  echo "rsync -a --update --delete -v --exclude '.Trash/*' "$REMOTEROOT" "$LOCALROOT""
  echo "The root directory ($LOCALROOT) can be specified or not"
  echo "Spaces in directory names are allowed by must be proceeded with a backslash (\) symbol"
  exit 1
elif [ -z "$1" ] # no directory has been spcified
then
  LOCALFOLDER=$LOCALROOT
  REMOTEFOLDER=$REMOTEROOT
  echo "Checking for files that are new or newer on GoogleDrive using rsync"
  echo ""
  idfiles=$(rsync --dry-run -a --delete -v --exclude=".*" $REMOTEROOT $LOCALROOT )
  idfiles=$(echo "$idfiles" | grep -v \(DRY\ RUN\)) # cleaning up some unecessary lines
  idfiles=$(echo "$idfiles" | grep -v ^sent) # cleaning up some unecessary lines
  delfiles=$(echo "$idfiles" | grep deleting) # just the files to be deleted
  addfiles=$(echo "$idfiles" | grep -v deleting) # just the file to be added
  echo "$addfiles"
  echo "$delfiles"
  echo ""
  echo -n "Should these changes be made to $LOCALROOT? (y/N) "
  read download
  if [ "$download" == "y" ] || [ "$download" == "Y" ]
  then
    echo "ok, will download"
  else
    echo "No changes made"
    exit
  fi
else
  ld=$1 # local directory, need this because $1 cannot be edited
  if [ $1 == "." ] # using local directory
  then
    ld=$(pwd)
  fi
  n1=$(echo "$ld" | sed -r 's/\\//g') # replace all \ with nothing
  n2=$(echo "$n1" | sed -r 's/\/home\/peter\/local_GoogleDrive\///g') # remove local folder if provided
  n3=$(echo "$n2" | sed -r 's/\/$//g') #remove the last / if provided
#  n4=$(echo "$n3" | sed -r 's/ /\\ /g') #replace empty spaces with \<space>
#  n5=$(echo "$n4" | sed -r 's/\(/\\\(/g') #replace ( withe \)
#  n6=$(echo "$n5" | sed -r 's/\)/\\\)/g') #replace ( withe \)

  LOCALFOLDER="$LOCALROOT$n3/"
  REMOTEFOLDER="$REMOTEROOT$n3/"
fi

### run the rsync command
echo "Updating LOCAL files (5 second delay)"
sleep 5
rsync -a --delete -v --exclude=".*" "$REMOTEFOLDER" "$LOCALFOLDER"
exit 1
