#!/bin/bash
# ug = update google -
# ugr = update remote folder with local folder data

LOCALROOT="/home/peter/local_GoogleDrive/" #root directory of local folder
REMOTEROOT="/home/peter/GoogleDrive/" #root directory of GoogleDrive folder

### Test if command line argument has been provided and set to and from folder
### path accordingly
if [ -z "$1" ]
then
  LOCALFOLDER=$LOCALROOT
  REMOTEFOLDER=$REMOTEROOT
else
  LOCALFOLDER="$LOCALROOT$1/"
  REMOTEFOLDER="$REMOTEROOT$1/"
fi

if [ "$1" == "-h" ] # looking for help
then
  echo "This script updates folder $REMOTEROOT with the content of $LOCALROOT with deletion"
  echo "By default all the folders are updated, but a specific folder can be specied on the command line"
  echo "The command that will executed by default is:"
  echo "rsync -a --update --delete -v --exclude '.Trash/*' $LOCALROOT $REMOTEROOT"
else
  echo "Changing files ON GOOGLE DRIVE (5 second delay)
  sleep 5
  rsync -a --update --delete -v --exclude '.Trash/*' $LOCALFOLDER $REMOTEFOLDER
fi
